name: expense_tracker
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  bloc: ^8.1.4
  firebase_core: ^2.30.1
  flutter:
    sdk: flutter
  flutter_bloc: 8.1.5
  flutter_dotenv: ^5.1.0
  flutter_native_splash: ^2.4.0
  mailer: ^6.1.0
  meta: ^1.11.0
  shared_preferences: ^2.2.3
  sqflite: ^2.3.3
  path: ^1.9.0
  flutter_launcher_icons: ^0.13.1
  pin_code_fields: ^8.0.1
  device_preview: ^1.1.0
  cloud_firestore: ^4.17.2
  fl_chart: ^0.67.0
  dio: ^5.4.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - 'assets/images/expense_tracker_image.png'
    - 'assets/images/dashboard_screenshot.png'
    - 'assets/images/wallet.png'
    - 'assets/images/person_with_app.png'
    - .env

flutter_native_splash:
  color: "#1b383a"
  image: "assets/images/logo.png"
  ios: false

flutter_launcher_icons:
  ios: true
  android: true
  image_path_android: "assets/images/logo.png"
  image_path_ios: "assets/images/logo.png"
